# Generated by Django 4.1.7 on 2023-03-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('description', models.TextField(verbose_name='отзыв')),
                ('quality', models.CharField(choices=[('плохое', 'плохое'), ('среднее', 'среднее'), ('удовлетворительное', 'удовлетворительное'), ('хорошее', 'хорошее'), ('отличное', 'отличное')], default='удовлетворительное', max_length=20, verbose_name='качество')),
                ('atmosphere', models.CharField(choices=[('плохая', 'плохая'), ('средняя', 'средняя'), ('удовлетворительная', 'удовлетворительная'), ('хорошая', 'хорошая'), ('отличная', 'отличная')], default='удовлетворительная', max_length=20, verbose_name='атмосфера')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
