# Generated by Django 4.1.7 on 2023-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
