# Generated by Django 4.1.7 on 2023-04-21 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallary",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галереии"},
        ),
    ]
