# Generated by Django 4.1.7 on 2023-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_alter_gallary_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="position",
            field=models.CharField(default=1, max_length=50, verbose_name="Позиция"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallary",
            name="photo",
            field=models.ImageField(upload_to="Galary/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="photo",
            field=models.ImageField(upload_to="Team/%Y/%m/%d/"),
        ),
    ]
